--The code must be like below:
SELECT CUSTOMER_KEY, 
oreplace(COALESCE(CUSTOMER_FIRST_NAME,''),' ','') AS CUSTOMER_FIRST_NAME,
oreplace(COALESCE(CUSTOMER_MID_NAME,''),' ','') AS CUSTOMER_MID_NAME
oreplace(COALESCE(CUSTOMER_LAST_NAME,''),' ','') AS CUSTOMER_LAST_NAME
from  CST.001_CUSTOMER;

--But DataStage converts the code like below:
SELECT CUSTOMER_KEY, 
oreplace(COALESCE(CUSTOMER_FIRST_NAME,'),' ',') AS CUSTOMER_FIRST_NAME,
oreplace(COALESCE(CUSTOMER_MID_NAME,'),' ',') AS CUSTOMER_MID_NAME
oreplace(COALESCE(CUSTOMER_LAST_NAME,'),' ',') AS CUSTOMER_LAST_NAME
from  CST.001_CUSTOMER;
